import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  Form,
  Input,
  InputNumber,
  Select,
  Button,
  Card,
  Space,
  Typography,
  App,
  Tooltip,
  Spin,
  Tag,
  Alert,
  Switch,
} from 'antd';
import {
  CheckCircle,
  XCircle,
  Loader2,
  Info,
  Wand2,
  RefreshCw,
  Rss,
  X,
} from 'lucide-react';
import { channelsApi } from '../api/channels';
import type { FieldMapping, PreviewEntry } from '../types';

type Mode = 'create' | 'edit';
type SidebarStatus = 'streaming' | 'done' | 'error' | 'idle';

const { Title, Text } = Typography;
const DEFAULT_FIELD_MAPPING_TEXT = JSON.stringify(
  {
    list_locator: { source: 'entries' },
    field_mappings: {
      title_cn: { source: 'title' },
      torrent_url: { source: 'link' },
      detail_url: { source: 'link' },
      published_at: { source: 'published', transform: 'iso_datetime' },
      resolution: { source: 'title', regex: '(720p|1080p|2160p|4K)', group: 1 },
      episode: { source: 'title', regex: '[第\\s]?(\\d{1,4})[话話集集]?', group: 1, transform: 'int' },
    },
  },
  null,
  2,
);

export default function ChannelForm() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const mode: Mode = id ? 'edit' : 'create';

  const [form] = Form.useForm();
  const { message } = App.useApp();
  const [saving, setSaving] = useState(false);
  const savingRef = useRef(false);
  const formTokenRef = useRef<string | null>(null);

  // URL validation (create mode)
  const [urlStatus, setUrlStatus] = useState<'idle' | 'checking' | 'valid' | 'invalid'>('idle');
  const [urlMessage, setUrlMessage] = useState('');
  const [downloadableCount, setDownloadableCount] = useState(0);
  const [loading, setLoading] = useState(mode === 'edit');

  // Field mapping (stored as JSON string for edit/view; generated by AI for create)
  const [fieldMapping, setFieldMapping] = useState<FieldMapping | null>(null);
  const [fieldMappingText, setFieldMappingText] = useState<string>(
    mode === 'create' ? DEFAULT_FIELD_MAPPING_TEXT : '',
  );
  const [analyzing, setAnalyzing] = useState(false);

  // Sidebar streaming
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [streamText, setStreamText] = useState('');
  const [sidebarStatus, setSidebarStatus] = useState<SidebarStatus>('idle');
  const [sidebarError, setSidebarError] = useState('');
  const streamBodyRef = useRef<HTMLDivElement>(null);

  // Feed preview
  const [previewEntries, setPreviewEntries] = useState<PreviewEntry[]>([]);
  const [previewParsed, setPreviewParsed] = useState<Record<string, unknown>[]>([]);
  const [previewLoading, setPreviewLoading] = useState(false);

  const fetchPreview = useCallback(
    async (url: string, fm: FieldMapping | null) => {
      if (!url) return;
      setPreviewLoading(true);
      try {
        const res = await channelsApi.previewFeed(url, fm);
        if (res.success && res.data) {
          setPreviewEntries(res.data.entries || []);
          setPreviewParsed(res.data.parsed || []);
        }
      } finally {
        setPreviewLoading(false);
      }
    },
    [],
  );

  // Auto-scroll stream
  useEffect(() => {
    if (streamBodyRef.current) {
      streamBodyRef.current.scrollTop = streamBodyRef.current.scrollHeight;
    }
  }, [streamText]);

  useEffect(() => {
    channelsApi.getFormToken().then((r) => {
      if (r.success) formTokenRef.current = r.data.token;
    });
  }, []);

  // Load for edit
  useEffect(() => {
    if (mode === 'edit' && id) {
      channelsApi.get(id).then((r) => {
        if (r.success) {
          const ch = r.data;
          form.setFieldsValue({
            name: ch.name,
            url: ch.url,
            fetch_interval: ch.fetch_interval,
            status: ch.status,
            metadata_agent_enabled: ch.metadata_agent_enabled ?? true,
          });
          if (ch.field_mapping) {
            setFieldMapping(ch.field_mapping as FieldMapping);
            setFieldMappingText(JSON.stringify(ch.field_mapping, null, 2));
            fetchPreview(ch.url, ch.field_mapping as FieldMapping);
          } else {
            fetchPreview(ch.url, null);
          }
        } else {
          message.error(t('channels.loadFailed'));
          navigate('/channels');
        }
        setLoading(false);
      });
    }
  }, [mode, id, form, fetchPreview, message, navigate]);

  // Auto-trigger field mapping analysis after URL validation succeeds (create mode only)
  const autoAnalyzeTriggered = useRef(false);
  useEffect(() => {
    if (
      mode === 'create' &&
      urlStatus === 'valid' &&
      !fieldMappingText.trim() &&
      !autoAnalyzeTriggered.current &&
      !analyzing
    ) {
      autoAnalyzeTriggered.current = true;
      handleAnalyze();
    }
  }, [mode, urlStatus, analyzing, fieldMappingText]);
  useEffect(() => {
    if (urlStatus === 'idle' || urlStatus === 'checking') {
      autoAnalyzeTriggered.current = false;
    }
  }, [urlStatus]);

  const validateUrl = async () => {
    const url = form.getFieldValue('url');
    if (!url) return;
    setUrlStatus('checking');
    const res = await channelsApi.validateUrl(url);
    if (res.success && res.data.valid) {
      setUrlStatus('valid');
      setDownloadableCount(res.data.downloadable_count);
      setUrlMessage(
        t('channels.validFeed', { count: res.data.item_count, torrent: res.data.downloadable_count }),
      );
      fetchPreview(url, null);
    } else {
      setUrlStatus('invalid');
      setUrlMessage(res.data?.message || res.error?.message || t('channels.invalidUrl'));
    }
  };

  const closeSidebar = useCallback(() => {
    setSidebarOpen(false);
  }, []);

  /** Parse SSE stream */
  const consumeStream = async (response: Response, onDone: (fm: FieldMapping) => void) => {
    if (!response.body) throw new Error('No response body');
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() || '';
      for (const line of lines) {
        if (line.startsWith('data: ')) {
          try {
            const data = JSON.parse(line.slice(6));
            if (data.type === 'delta') {
              setStreamText((p) => p + (data.content || ''));
            } else if (data.type === 'done') {
              const mapping = data.field_mapping as FieldMapping | undefined;
              if (mapping) {
                setFieldMapping(mapping);
                setFieldMappingText(JSON.stringify(mapping, null, 2));
                setSidebarStatus('done');
                onDone(mapping);
              } else {
                setSidebarStatus('error');
                setSidebarError(t('channels.noMapping'));
              }
            } else if (data.type === 'error') {
              setSidebarStatus('error');
              setSidebarError(data.message || t('channels.analysisFailed'));
            }
          } catch {
            /* ignore */
          }
        }
      }
    }
  };

  const handleAnalyze = async () => {
    const url = mode === 'edit' ? form.getFieldValue('url') : form.getFieldValue('url');
    if (!url) {
      message.warning(t('channels.enterUrlFirst'));
      return;
    }
    setAnalyzing(true);
    setStreamText('');
    setSidebarError('');
    setSidebarStatus('streaming');
    setSidebarOpen(true);

    try {
      const res =
        mode === 'edit' && id
          ? await channelsApi.analyzeStream(id)
          : await channelsApi.analyzeUrlStream(url);
      if (!res.ok) {
        let err = t('channels.requestFailed');
        try {
          const body = await res.json();
          err = body?.error?.message || err;
        } catch {
          /* ignore */
        }
        setSidebarStatus('error');
        setSidebarError(err);
        setAnalyzing(false);
        return;
      }
      await consumeStream(res, (mapping) => {
        message.success(t('channels.mappingGenerated'));
        fetchPreview(url, mapping);
      });
    } catch {
      setSidebarStatus('error');
      setSidebarError(t('channels.analysisFailed'));
    }
    setAnalyzing(false);
  };

  const handleSubmit = async (values: {
    name: string;
    url: string;
    fetch_interval: number;
    status?: string;
    metadata_agent_enabled?: boolean;
  }) => {
    // Parse field mapping text if edit mode
    let fm: FieldMapping | null = fieldMapping;
    if (fieldMappingText) {
      try {
        fm = JSON.parse(fieldMappingText);
      } catch {
        message.error(t('channels.mappingJsonError'));
        return;
      }
    }

    if (!fm || !fm.field_mappings || Object.keys(fm.field_mappings).length === 0) {
      message.error(t('channels.mappingRequired'));
      return;
    }

    if (savingRef.current) return;
    savingRef.current = true;
    setSaving(true);

    const token = formTokenRef.current;
    formTokenRef.current = null;

    try {
      if (mode === 'create') {
        if (urlStatus === 'invalid') {
          message.error(t('channels.rssValidationFailed'));
          savingRef.current = false;
          setSaving(false);
          return;
        }
        const res = await channelsApi.create(
          {
            name: values.name,
            url: values.url,
            fetch_interval: values.fetch_interval,
            type: 'rss_feed',
            field_mapping: fm,
            metadata_agent_enabled: values.metadata_agent_enabled ?? true,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success(t('channels.created'));
          navigate('/channels');
        } else {
          message.error(res.error?.message || t('channels.createFailed'));
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      } else if (id) {
        const res = await channelsApi.update(
          id,
          {
            name: values.name,
            fetch_interval: values.fetch_interval,
            status: (values.status as 'active' | 'inactive') || 'active',
            field_mapping: fm,
            metadata_agent_enabled: values.metadata_agent_enabled ?? true,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success(t('channels.updated'));
          navigate(`/channels/${id}`);
        } else {
          message.error(res.error?.message || t('channels.updateFailed'));
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      }
    } finally {
      savingRef.current = false;
      setSaving(false);
    }
  };

  const parseFieldMappingText = (): FieldMapping | null => {
    if (!fieldMappingText.trim()) return fieldMapping;
    try {
      const fm = JSON.parse(fieldMappingText);
      setFieldMapping(fm);
      return fm;
    } catch {
      message.error(t('channels.mappingJsonError'));
      return null;
    }
  };

  if (loading) {
    return <Spin style={{ display: 'flex', justifyContent: 'center', padding: 48 }} />;
  }

  return (
    <div className="channel-form-layout">
      <div className="channel-form-main">
        <Title level={3} style={{ marginBottom: 24 }}>
          {mode === 'create' ? t('channels.newChannel') : t('channels.editChannel')}
        </Title>

        <Card>
          <Form
            form={form}
            layout="vertical"
            onFinish={handleSubmit}
            initialValues={
              mode === 'create'
                ? { name: '', url: '', fetch_interval: 1800, metadata_agent_enabled: true }
                : undefined
            }
          >
            <Form.Item
              name="name"
              label={t('common.name')}
              rules={[{ required: true, message: t('channels.pleaseEnterName') }]}
            >
              <Input placeholder={t('channels.nameExample')} />
            </Form.Item>

            <Form.Item
              name="url"
              label={t('channels.rssUrl')}
              rules={
                mode === 'create' ? [{ required: true, message: t('channels.enterRssUrl') }] : []
              }
            >
              {mode === 'edit' ? (
                <Input disabled style={{ color: '#93939f' }} />
              ) : (
                <Space.Compact style={{ width: '100%' }}>
                  <Input
                    placeholder="https://mikanani.me/RSS/..."
                    onChange={() => setUrlStatus('idle')}
                  />
                  <Button onClick={validateUrl}>{t('channels.validate')}</Button>
                </Space.Compact>
              )}
            </Form.Item>

            {urlStatus === 'checking' && (
              <div style={{ marginBottom: 16, display: 'flex', gap: 6, alignItems: 'center' }}>
                <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />
                <Text type="secondary" style={{ fontSize: 12 }}>
                  {t('channels.validating')}
                </Text>
              </div>
            )}
            {urlStatus === 'valid' && (
              <div style={{ marginBottom: 16 }}>
                <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                  <CheckCircle size={14} color="#003c33" />
                  <Text style={{ fontSize: 12, color: '#003c33' }}>{urlMessage}</Text>
                </div>
                {downloadableCount === 0 && (
                  <Text style={{ fontSize: 12, color: '#ff7759' }}>
                    {t('channels.noTorrentWarning')}
                  </Text>
                )}
              </div>
            )}
            {urlStatus === 'invalid' && (
              <div style={{ marginBottom: 16, display: 'flex', gap: 6, alignItems: 'center' }}>
                <XCircle size={14} color="#b30000" />
                <Text style={{ fontSize: 12, color: '#b30000' }}>{urlMessage}</Text>
              </div>
            )}

            <Form.Item name="fetch_interval" label={t('channels.fetchIntervalSec')} rules={[{ required: true }]}>
              <InputNumber min={60} style={{ width: 180 }} />
            </Form.Item>

            <Form.Item
              name="metadata_agent_enabled"
              label={t('channels.autoMetadataLLM')}
              valuePropName="checked"
              tooltip={t('channels.metadataLLMDesc')}
            >
              <Switch checkedChildren={t('common.on')} unCheckedChildren={t('common.off')} />
            </Form.Item>

            {mode === 'edit' && (
              <Form.Item name="status" label={t('common.status')}>
                <Select
                  options={[
                    { value: 'active', label: t('status.active') },
                    { value: 'inactive', label: t('status.inactive') },
                  ]}
                  style={{ width: 160 }}
                />
              </Form.Item>
            )}

            {/* Field mapping */}
            <div style={{ marginBottom: 8 }}>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: 8,
                }}
              >
                <Space size={6}>
                  <Text strong>{t('channels.fieldMapping')}</Text>
                  <Tooltip title={t('channels.fieldMappingDesc')}>
                    <Info size={13} style={{ color: '#93939f' }} />
                  </Tooltip>
                </Space>
                <Space size={8}>
                  <Button
                    size="small"
                    icon={<RefreshCw size={13} />}
                    onClick={() => {
                      const url = form.getFieldValue('url');
                      const fm = parseFieldMappingText();
                      if (url && fm) fetchPreview(url, fm);
                    }}
                  >
                    {t('channels.preview')}
                  </Button>
                  <Button
                    size="small"
                    icon={analyzing ? <Spin size="small" /> : <Wand2 size={13} />}
                    loading={analyzing}
                    onClick={handleAnalyze}
                    disabled={mode === 'create' && urlStatus !== 'valid'}
                  >
                    {fieldMapping ? t('channels.reAnalyze') : t('channels.analyze')}
                  </Button>
                </Space>
              </div>

              <Input.TextArea
                value={fieldMappingText}
                onChange={(e) => setFieldMappingText(e.target.value)}
                rows={12}
                style={{
                  fontFamily: 'monospace',
                  fontSize: 12,
                  background: '#ffffff',
                }}
                placeholder={DEFAULT_FIELD_MAPPING_TEXT}
              />
              {!fieldMappingText && (
                <Text type="secondary" style={{ fontSize: 12, display: 'block', marginTop: 6 }}>
                  {t('channels.aiPromptHint')}
                </Text>
              )}
            </div>

            {!fieldMapping && !fieldMappingText.trim() && (
              <Alert
                type="warning"
                showIcon
                style={{ marginTop: 12 }}
                message={t('channels.mappingMandatory')}
                description={t('channels.mappingMandatoryDesc')}
              />
            )}

            <Form.Item style={{ marginTop: 24 }}>
              <Space>
                <Button type="primary" htmlType="submit" loading={saving}>
                  {mode === 'create' ? t('channels.createChannel') : t('common.saveChanges')}
                </Button>
                <Button onClick={() => navigate(mode === 'edit' ? `/channels/${id}` : '/channels')}>
                  {t('common.cancel')}
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>
      </div>

      {/* Right column */}
      <div className="channel-form-right">
        {/* Stream sidebar */}
        <div className={`channel-form-stream ${sidebarOpen ? 'open' : ''}`}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '10px 16px',
              borderBottom: '1px solid #eeece7',
            }}
          >
            <Space>
              <Wand2 size={14} style={{ color: '#93939f' }} />
              <Text strong style={{ fontSize: 13 }}>
                {t('channels.analyze')}
              </Text>
            </Space>
            <Button
              type="text"
              size="small"
              icon={<X size={14} />}
              onClick={closeSidebar}
              style={{ color: '#93939f' }}
            />
          </div>
          <div
            ref={streamBodyRef}
            style={{
              flex: 1,
              overflow: 'auto',
              padding: '12px 16px',
              fontFamily: 'monospace',
              fontSize: 12,
              lineHeight: 1.65,
              color: '#93939f',
              whiteSpace: 'pre-wrap',
            }}
          >
            {streamText}
            {sidebarStatus === 'streaming' && <span className="stream-cursor" />}
            {sidebarStatus === 'error' && (
              <div style={{ color: '#b30000' }}>{sidebarError}</div>
            )}
          </div>
          <div
            style={{
              padding: '8px 16px',
              borderTop: '1px solid #eeece7',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}
          >
            {sidebarStatus === 'streaming' && (
              <Space>
                <Loader2 size={13} style={{ color: '#1863dc', animation: 'spin 1s linear infinite' }} />
                <Text style={{ fontSize: 12, color: '#1863dc' }}>{t('channels.analyzing')}</Text>
              </Space>
            )}
            {sidebarStatus === 'done' && (
              <Space>
                <CheckCircle size={13} color="#003c33" />
                <Text style={{ fontSize: 12, color: '#003c33' }}>{t('channels.analysisDone')}</Text>
              </Space>
            )}
            {sidebarStatus === 'error' && (
              <Space>
                <XCircle size={13} color="#b30000" />
                <Text style={{ fontSize: 12, color: '#b30000' }}>{sidebarError}</Text>
              </Space>
            )}
          </div>
        </div>

        {/* Feed Preview */}
        <div className="channel-form-preview">
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '14px 16px',
              borderBottom: '1px solid #eeece7',
            }}
          >
            <Space>
              <Rss size={14} style={{ color: '#93939f' }} />
              <Text strong style={{ fontSize: 13 }}>
                {t('channels.preview')}
              </Text>
              {previewEntries.length > 0 && (
                <Text style={{ fontSize: 12, color: '#93939f' }}>
                  {previewEntries.length} {t('channels.entries')}
                </Text>
              )}
            </Space>
            {previewEntries.length > 0 && !previewLoading && (
              <Button
                type="text"
                size="small"
                icon={<RefreshCw size={13} />}
                onClick={() => {
                  const url = form.getFieldValue('url');
                  if (url) fetchPreview(url, fieldMapping);
                }}
                style={{ color: '#93939f' }}
              />
            )}
          </div>
          <div style={{ flex: 1, overflow: 'auto', padding: 0 }}>
            {previewLoading ? (
              <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
                <Spin />
              </div>
            ) : previewEntries.length === 0 ? (
              <div style={{ padding: 48, textAlign: 'center', color: '#75758a', fontSize: 13 }}>
                {mode === 'edit' ? t('common.loading') : t('channels.enterUrlFirst')}
              </div>
            ) : (
              previewEntries.slice(0, 30).map((entry, i) => {
                const parsed = previewParsed[i] || {};
                const hasParsed = Object.keys(parsed).length > 0;
                return (
                  <div
                    key={i}
                    style={{
                      padding: '12px 16px',
                      borderBottom: '1px solid #eeece7',
                    }}
                  >
                    <Text
                      style={{ fontSize: 13, display: 'block', marginBottom: 4, wordBreak: 'break-word' }}
                    >
                      {entry.title || 'Untitled'}
                    </Text>
                    {entry.published && (
                      <Text style={{ fontSize: 11, color: '#93939f', display: 'block', marginBottom: hasParsed ? 6 : 0 }}>
                        {new Date(entry.published).toLocaleDateString()}
                      </Text>
                    )}
                    {hasParsed && (
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                        {Object.entries(parsed)
                          .filter(([, v]) => v != null && v !== '')
                          .map(([k, v]) => (
                            <Tag
                              key={k}
                              style={{
                                fontSize: 11,
                                background: '#f7f7f5',
                                border: '1px solid #d9d9dd',
                                color: '#93939f',
                                marginInlineEnd: 0,
                              }}
                            >
                              <span style={{ color: '#93939f' }}>{k}:</span> {String(v)}
                            </Tag>
                          ))}
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
