import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Form,
  Input,
  InputNumber,
  Select,
  Button,
  Switch,
  Card,
  Space,
  Typography,
  App,
  Tooltip,
  Spin,
  Tag,
  Alert,
} from 'antd';
import {
  CheckCircle,
  XCircle,
  Loader2,
  Info,
  Wand2,
  RefreshCw,
  Rss,
  X,
} from 'lucide-react';
import { channelsApi } from '../api/channels';
import type { FieldMapping, PreviewEntry } from '../types';

type Mode = 'create' | 'edit';
type SidebarStatus = 'streaming' | 'done' | 'error' | 'idle';

const { Title, Text } = Typography;

export default function ChannelForm() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const mode: Mode = id ? 'edit' : 'create';

  const [form] = Form.useForm();
  const { message } = App.useApp();
  const [saving, setSaving] = useState(false);
  const savingRef = useRef(false);
  const formTokenRef = useRef<string | null>(null);

  // URL validation (create mode)
  const [urlStatus, setUrlStatus] = useState<'idle' | 'checking' | 'valid' | 'invalid'>('idle');
  const [urlMessage, setUrlMessage] = useState('');
  const [downloadableCount, setDownloadableCount] = useState(0);
  const [loading, setLoading] = useState(mode === 'edit');

  // Metadata & title
  const [metadataSource, setMetadataSource] = useState<'none' | 'llm'>('llm');
  const [titleMethod, setTitleMethod] = useState<'none' | 'regex' | 'llm'>('none');
  const [titleRegex, setTitleRegex] = useState('');
  const [generatingRegex, setGeneratingRegex] = useState(false);

  // Field mapping (stored as JSON string for edit/view; generated by AI for create)
  const [fieldMapping, setFieldMapping] = useState<FieldMapping | null>(null);
  const [fieldMappingText, setFieldMappingText] = useState<string>('');
  const [analyzing, setAnalyzing] = useState(false);

  // Sidebar streaming
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [streamText, setStreamText] = useState('');
  const [sidebarStatus, setSidebarStatus] = useState<SidebarStatus>('idle');
  const [sidebarError, setSidebarError] = useState('');
  const streamBodyRef = useRef<HTMLDivElement>(null);

  // Feed preview
  const [previewEntries, setPreviewEntries] = useState<PreviewEntry[]>([]);
  const [previewParsed, setPreviewParsed] = useState<Record<string, unknown>[]>([]);
  const [previewLoading, setPreviewLoading] = useState(false);

  const fetchPreview = useCallback(
    async (url: string, fm: FieldMapping | null) => {
      if (!url) return;
      setPreviewLoading(true);
      try {
        const res = await channelsApi.previewFeed(url, fm);
        if (res.success && res.data) {
          setPreviewEntries(res.data.entries || []);
          setPreviewParsed(res.data.parsed || []);
        }
      } finally {
        setPreviewLoading(false);
      }
    },
    [],
  );

  // Auto-scroll stream
  useEffect(() => {
    if (streamBodyRef.current) {
      streamBodyRef.current.scrollTop = streamBodyRef.current.scrollHeight;
    }
  }, [streamText]);

  useEffect(() => {
    channelsApi.getFormToken().then((r) => {
      if (r.success) formTokenRef.current = r.data.token;
    });
  }, []);

  // Load for edit
  useEffect(() => {
    if (mode === 'edit' && id) {
      channelsApi.get(id).then((r) => {
        if (r.success) {
          const ch = r.data;
          form.setFieldsValue({
            name: ch.name,
            url: ch.url,
            fetch_interval: ch.fetch_interval,
            status: ch.status,
          });
          setMetadataSource(ch.metadata_source || 'llm');
          setTitleMethod(ch.title_extraction_method || 'none');
          setTitleRegex(ch.title_extraction_regex || '');
          if (ch.field_mapping) {
            setFieldMapping(ch.field_mapping as FieldMapping);
            setFieldMappingText(JSON.stringify(ch.field_mapping, null, 2));
            fetchPreview(ch.url, ch.field_mapping as FieldMapping);
          } else {
            fetchPreview(ch.url, null);
          }
        } else {
          message.error('加载频道失败');
          navigate('/channels');
        }
        setLoading(false);
      });
    }
  }, [mode, id, form, fetchPreview, message, navigate]);

  const validateUrl = async () => {
    const url = form.getFieldValue('url');
    if (!url) return;
    setUrlStatus('checking');
    const res = await channelsApi.validateUrl(url);
    if (res.success && res.data.valid) {
      setUrlStatus('valid');
      setDownloadableCount(res.data.downloadable_count);
      setUrlMessage(
        `有效 RSS：共 ${res.data.item_count} 条，${res.data.downloadable_count} 条含下载链接`,
      );
      fetchPreview(url, null);
    } else {
      setUrlStatus('invalid');
      setUrlMessage(res.data?.message || res.error?.message || 'URL 无效');
    }
  };

  const closeSidebar = useCallback(() => {
    setSidebarOpen(false);
  }, []);

  /** Parse SSE stream */
  const consumeStream = async (response: Response, onDone: (fm: FieldMapping) => void) => {
    if (!response.body) throw new Error('No response body');
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() || '';
      for (const line of lines) {
        if (line.startsWith('data: ')) {
          try {
            const data = JSON.parse(line.slice(6));
            if (data.type === 'delta') {
              setStreamText((p) => p + (data.content || ''));
            } else if (data.type === 'done') {
              const mapping = data.field_mapping as FieldMapping | undefined;
              if (mapping) {
                setFieldMapping(mapping);
                setFieldMappingText(JSON.stringify(mapping, null, 2));
                setSidebarStatus('done');
                onDone(mapping);
              } else {
                setSidebarStatus('error');
                setSidebarError('未生成字段映射，请确认 LLM 配置');
              }
            } else if (data.type === 'error') {
              setSidebarStatus('error');
              setSidebarError(data.message || '分析失败');
            }
          } catch {
            /* ignore */
          }
        }
      }
    }
  };

  const handleAnalyze = async () => {
    const url = mode === 'edit' ? form.getFieldValue('url') : form.getFieldValue('url');
    if (!url) {
      message.warning('请先输入 RSS URL');
      return;
    }
    setAnalyzing(true);
    setStreamText('');
    setSidebarError('');
    setSidebarStatus('streaming');
    setSidebarOpen(true);

    try {
      const res =
        mode === 'edit' && id
          ? await channelsApi.analyzeStream(id)
          : await channelsApi.analyzeUrlStream(url);
      if (!res.ok) {
        let err = '请求失败';
        try {
          const body = await res.json();
          err = body?.error?.message || err;
        } catch {
          /* ignore */
        }
        setSidebarStatus('error');
        setSidebarError(err);
        setAnalyzing(false);
        return;
      }
      await consumeStream(res, (mapping) => {
        message.success('字段映射已生成');
        fetchPreview(url, mapping);
      });
    } catch {
      setSidebarStatus('error');
      setSidebarError('分析失败，请检查 LLM 配置');
    }
    setAnalyzing(false);
  };

  const handleGenerateRegex = async () => {
    if (!id) return;
    setGeneratingRegex(true);
    const res = await channelsApi.generateTitleRegex(id);
    setGeneratingRegex(false);
    if (res.success && res.data?.regex) {
      setTitleRegex(res.data.regex);
      message.success('已生成标题清洗正则');
    } else {
      message.error(res.error?.message || '生成失败');
    }
  };

  const handleSubmit = async (values: {
    name: string;
    url: string;
    fetch_interval: number;
    status?: string;
  }) => {
    // Parse field mapping text if edit mode
    let fm: FieldMapping | null = fieldMapping;
    if (fieldMappingText) {
      try {
        fm = JSON.parse(fieldMappingText);
      } catch {
        message.error('字段映射 JSON 格式错误');
        return;
      }
    }

    if (!fm || !fm.field_mappings || Object.keys(fm.field_mappings).length === 0) {
      message.error('字段映射为必填项，请先完成 AI 自动分析或手动填写 JSON');
      return;
    }

    if (savingRef.current) return;
    savingRef.current = true;
    setSaving(true);

    const token = formTokenRef.current;
    formTokenRef.current = null;

    try {
      if (mode === 'create') {
        if (urlStatus === 'invalid') {
          message.error('RSS URL 校验失败，请修正后再提交');
          savingRef.current = false;
          setSaving(false);
          return;
        }
        const res = await channelsApi.create(
          {
            name: values.name,
            url: values.url,
            fetch_interval: values.fetch_interval,
            type: 'rss_feed',
            field_mapping: fm,
            title_extraction_method: titleMethod,
            title_extraction_regex: titleMethod === 'regex' ? titleRegex || null : null,
            metadata_source: metadataSource,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success('频道已创建');
          navigate('/channels');
        } else {
          message.error(res.error?.message || '创建失败');
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      } else if (id) {
        const res = await channelsApi.update(
          id,
          {
            name: values.name,
            fetch_interval: values.fetch_interval,
            status: (values.status as 'active' | 'inactive') || 'active',
            field_mapping: fm,
            title_extraction_method: titleMethod,
            title_extraction_regex: titleMethod === 'regex' ? titleRegex || null : null,
            metadata_source: metadataSource,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success('频道已更新');
          navigate(`/channels/${id}`);
        } else {
          message.error(res.error?.message || '更新失败');
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      }
    } finally {
      savingRef.current = false;
      setSaving(false);
    }
  };

  if (loading) {
    return <Spin style={{ display: 'flex', justifyContent: 'center', padding: 48 }} />;
  }

  return (
    <div className="channel-form-layout">
      <div className="channel-form-main">
        <Title level={3} style={{ marginBottom: 24 }}>
          {mode === 'create' ? '新建频道' : '编辑频道'}
        </Title>

        <Card>
          <Form
            form={form}
            layout="vertical"
            onFinish={handleSubmit}
            initialValues={
              mode === 'create' ? { name: '', url: '', fetch_interval: 1800 } : undefined
            }
          >
            <Form.Item
              name="name"
              label="名称"
              rules={[{ required: true, message: '请输入频道名称' }]}
            >
              <Input placeholder="例如：蜜柑计划" />
            </Form.Item>

            <Form.Item
              name="url"
              label="RSS URL"
              rules={
                mode === 'create' ? [{ required: true, message: '请输入 RSS URL' }] : []
              }
            >
              {mode === 'edit' ? (
                <Input disabled style={{ color: '#93939f' }} />
              ) : (
                <Space.Compact style={{ width: '100%' }}>
                  <Input
                    placeholder="https://mikanani.me/RSS/..."
                    onChange={() => setUrlStatus('idle')}
                  />
                  <Button onClick={validateUrl}>验证</Button>
                </Space.Compact>
              )}
            </Form.Item>

            {urlStatus === 'checking' && (
              <div style={{ marginBottom: 16, display: 'flex', gap: 6, alignItems: 'center' }}>
                <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />
                <Text type="secondary" style={{ fontSize: 12 }}>
                  正在验证...
                </Text>
              </div>
            )}
            {urlStatus === 'valid' && (
              <div style={{ marginBottom: 16 }}>
                <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                  <CheckCircle size={14} color="#003c33" />
                  <Text style={{ fontSize: 12, color: '#003c33' }}>{urlMessage}</Text>
                </div>
                {downloadableCount === 0 && (
                  <Text style={{ fontSize: 12, color: '#ff7759' }}>
                    ⚠ 未找到可下载的资源链接
                  </Text>
                )}
              </div>
            )}
            {urlStatus === 'invalid' && (
              <div style={{ marginBottom: 16, display: 'flex', gap: 6, alignItems: 'center' }}>
                <XCircle size={14} color="#b30000" />
                <Text style={{ fontSize: 12, color: '#b30000' }}>{urlMessage}</Text>
              </div>
            )}

            <Form.Item name="fetch_interval" label="抓取间隔（秒）" rules={[{ required: true }]}>
              <InputNumber min={60} style={{ width: 180 }} />
            </Form.Item>

            {mode === 'edit' && (
              <Form.Item name="status" label="状态">
                <Select
                  options={[
                    { value: 'active', label: '活跃' },
                    { value: 'inactive', label: '停用' },
                  ]}
                  style={{ width: 160 }}
                />
              </Form.Item>
            )}

            {/* Metadata source */}
            <div style={{ marginBottom: 20 }}>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: 8,
                }}
              >
                <Space size={6}>
                  <Text strong>自动元数据搜索 (LLM)</Text>
                  <Tooltip title="本地匹配失败时调用 LLM 联网搜索元数据，会增加抓取延迟">
                    <Info size={13} style={{ color: '#93939f' }} />
                  </Tooltip>
                </Space>
                <Switch
                  checked={metadataSource === 'llm'}
                  onChange={(v) => setMetadataSource(v ? 'llm' : 'none')}
                  checkedChildren="开"
                  unCheckedChildren="关"
                />
              </div>
              <Text type="secondary" style={{ fontSize: 12 }}>
                {metadataSource === 'llm'
                  ? '本地匹配失败时将通过 LLM 联网搜索作品元数据'
                  : '关闭后不会自动搜索新作品；需要手动设置 metadata 搜索关键字并关联作品'}
              </Text>
            </div>

            {/* Title extraction */}
            <div style={{ marginBottom: 20 }}>
              <Text strong style={{ display: 'block', marginBottom: 8 }}>
                标题清洗方式
              </Text>
              <Select
                value={titleMethod}
                onChange={(v) => setTitleMethod(v)}
                style={{ width: '100%' }}
                options={[
                  { value: 'none', label: '不清洗 — 直接使用原始标题匹配' },
                  { value: 'regex', label: '正则表达式 — 自定义正则提取核心标题' },
                  { value: 'llm', label: 'LLM — AI 清洗标题（结果缓存）' },
                ]}
              />
              {titleMethod === 'regex' && (
                <div style={{ marginTop: 12 }}>
                  <Space.Compact style={{ width: '100%' }}>
                    <Input
                      value={titleRegex}
                      onChange={(e) => setTitleRegex(e.target.value)}
                      placeholder="正则表达式，需包含捕获组 1"
                    />
                    {mode === 'edit' && (
                      <Button
                        icon={<Wand2 size={14} />}
                        loading={generatingRegex}
                        onClick={handleGenerateRegex}
                      >
                        AI 生成
                      </Button>
                    )}
                  </Space.Compact>
                  <Text type="secondary" style={{ fontSize: 11, display: 'block', marginTop: 4 }}>
                    正则第一个捕获组将作为搜索标题
                  </Text>
                </div>
              )}
            </div>

            {/* Field mapping */}
            <div style={{ marginBottom: 8 }}>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  marginBottom: 8,
                }}
              >
                <Space size={6}>
                  <Text strong>字段映射</Text>
                  <Tooltip title="定义如何从 RSS entry 中提取结构化字段">
                    <Info size={13} style={{ color: '#93939f' }} />
                  </Tooltip>
                </Space>
                <Button
                  size="small"
                  icon={analyzing ? <Spin size="small" /> : <Wand2 size={13} />}
                  loading={analyzing}
                  onClick={handleAnalyze}
                  disabled={mode === 'create' && urlStatus !== 'valid'}
                >
                  {fieldMapping ? '重新分析' : 'AI 自动分析'}
                </Button>
              </div>

              {fieldMapping || fieldMappingText ? (
                <Input.TextArea
                  value={fieldMappingText || JSON.stringify(fieldMapping, null, 2)}
                  onChange={(e) => setFieldMappingText(e.target.value)}
                  rows={10}
                  style={{
                    fontFamily: 'monospace',
                    fontSize: 12,
                    background: '#ffffff',
                  }}
                  placeholder="AI 分析后将自动填充，或手动编辑 JSON"
                />
              ) : (
                <div
                  style={{
                    padding: 24,
                    border: '1px dashed #d9d9dd',
                    borderRadius: 8,
                    textAlign: 'center',
                    color: '#93939f',
                  }}
                >
                  {mode === 'create'
                    ? '请先验证 RSS URL，再使用"AI 自动分析"生成字段映射'
                    : '尚未配置字段映射，点击"AI 自动分析"生成'}
                </div>
              )}
            </div>

            {!fieldMapping && (
              <Alert
                type="warning"
                showIcon
                style={{ marginTop: 12 }}
                message="字段映射为必填项"
                description="没有字段映射，系统无法解析 RSS 条目，将无法下载任何资源。"
              />
            )}

            <Form.Item style={{ marginTop: 24 }}>
              <Space>
                <Button type="primary" htmlType="submit" loading={saving}>
                  {mode === 'create' ? '创建频道' : '保存更改'}
                </Button>
                <Button onClick={() => navigate(mode === 'edit' ? `/channels/${id}` : '/channels')}>
                  取消
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>
      </div>

      {/* Right column */}
      <div className="channel-form-right">
        {/* Stream sidebar */}
        <div className={`channel-form-stream ${sidebarOpen ? 'open' : ''}`}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '10px 16px',
              borderBottom: '1px solid #eeece7',
            }}
          >
            <Space>
              <Wand2 size={14} style={{ color: '#93939f' }} />
              <Text strong style={{ fontSize: 13 }}>
                AI 分析
              </Text>
            </Space>
            <Button
              type="text"
              size="small"
              icon={<X size={14} />}
              onClick={closeSidebar}
              style={{ color: '#93939f' }}
            />
          </div>
          <div
            ref={streamBodyRef}
            style={{
              flex: 1,
              overflow: 'auto',
              padding: '12px 16px',
              fontFamily: 'monospace',
              fontSize: 12,
              lineHeight: 1.65,
              color: '#93939f',
              whiteSpace: 'pre-wrap',
            }}
          >
            {streamText}
            {sidebarStatus === 'streaming' && <span className="stream-cursor" />}
            {sidebarStatus === 'error' && (
              <div style={{ color: '#b30000' }}>{sidebarError}</div>
            )}
          </div>
          <div
            style={{
              padding: '8px 16px',
              borderTop: '1px solid #eeece7',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}
          >
            {sidebarStatus === 'streaming' && (
              <Space>
                <Loader2 size={13} style={{ color: '#1863dc', animation: 'spin 1s linear infinite' }} />
                <Text style={{ fontSize: 12, color: '#1863dc' }}>分析中...</Text>
              </Space>
            )}
            {sidebarStatus === 'done' && (
              <Space>
                <CheckCircle size={13} color="#003c33" />
                <Text style={{ fontSize: 12, color: '#003c33' }}>分析完成</Text>
              </Space>
            )}
            {sidebarStatus === 'error' && (
              <Space>
                <XCircle size={13} color="#b30000" />
                <Text style={{ fontSize: 12, color: '#b30000' }}>{sidebarError}</Text>
              </Space>
            )}
          </div>
        </div>

        {/* Feed Preview */}
        <div className="channel-form-preview">
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '14px 16px',
              borderBottom: '1px solid #eeece7',
            }}
          >
            <Space>
              <Rss size={14} style={{ color: '#93939f' }} />
              <Text strong style={{ fontSize: 13 }}>
                预览
              </Text>
              {previewEntries.length > 0 && (
                <Text style={{ fontSize: 12, color: '#93939f' }}>
                  {previewEntries.length} 条
                </Text>
              )}
            </Space>
            {previewEntries.length > 0 && !previewLoading && (
              <Button
                type="text"
                size="small"
                icon={<RefreshCw size={13} />}
                onClick={() => {
                  const url = form.getFieldValue('url');
                  if (url) fetchPreview(url, fieldMapping);
                }}
                style={{ color: '#93939f' }}
              />
            )}
          </div>
          <div style={{ flex: 1, overflow: 'auto', padding: 0 }}>
            {previewLoading ? (
              <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
                <Spin />
              </div>
            ) : previewEntries.length === 0 ? (
              <div style={{ padding: 48, textAlign: 'center', color: '#75758a', fontSize: 13 }}>
                {mode === 'edit' ? '加载中...' : '验证 URL 后预览条目'}
              </div>
            ) : (
              previewEntries.slice(0, 30).map((entry, i) => {
                const parsed = previewParsed[i] || {};
                const hasParsed = Object.keys(parsed).length > 0;
                return (
                  <div
                    key={i}
                    style={{
                      padding: '12px 16px',
                      borderBottom: '1px solid #eeece7',
                    }}
                  >
                    <Text
                      style={{ fontSize: 13, display: 'block', marginBottom: 4, wordBreak: 'break-word' }}
                    >
                      {entry.title || 'Untitled'}
                    </Text>
                    {entry.published && (
                      <Text style={{ fontSize: 11, color: '#93939f', display: 'block', marginBottom: hasParsed ? 6 : 0 }}>
                        {new Date(entry.published).toLocaleDateString()}
                      </Text>
                    )}
                    {hasParsed && (
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                        {Object.entries(parsed)
                          .filter(([, v]) => v != null && v !== '')
                          .map(([k, v]) => (
                            <Tag
                              key={k}
                              style={{
                                fontSize: 11,
                                background: '#f7f7f5',
                                border: '1px solid #d9d9dd',
                                color: '#93939f',
                                marginInlineEnd: 0,
                              }}
                            >
                              <span style={{ color: '#93939f' }}>{k}:</span> {String(v)}
                            </Tag>
                          ))}
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
