import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import useDocumentTitle from '../hooks/useDocumentTitle';
import { Button, Card, Form, Space, Spin, Tabs, Tag, Typography, App } from 'antd';
import {
  CheckCircle,
  XCircle,
  Loader2,
  Rss,
  RefreshCw,
  Wand2,
  X,
} from 'lucide-react';
import { channelsApi } from '../api/channels';
import type { MetadataSourceOption } from '../api/channels';
import type { FieldMapping, MetadataSource, PreviewEntry } from '../types';
import BasicInfoTab, { type UrlStatus } from '../components/channel-form/BasicInfoTab';
import MetadataSearchTab from '../components/channel-form/MetadataSearchTab';
import ScheduleTab from '../components/channel-form/ScheduleTab';
import {
  DEFAULT_FALLBACK_SOURCES,
  DEFAULT_FIELD_MAPPING_TEXT,
  tabKeyForField,
} from '../components/channel-form/constants';

type Mode = 'create' | 'edit';
type SidebarStatus = 'streaming' | 'done' | 'error' | 'idle';
type TabKey = 'basic' | 'metadata' | 'schedule';

const { Title, Text } = Typography;

export default function ChannelForm() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const mode: Mode = id ? 'edit' : 'create';
  useDocumentTitle(t(mode === 'edit' ? 'channels.editChannel' : 'channels.newChannel'));

  const [form] = Form.useForm();
  const { message } = App.useApp();
  const [saving, setSaving] = useState(false);
  const savingRef = useRef(false);
  const formTokenRef = useRef<string | null>(null);

  // Active tab + per-tab validation errors (red dots on tab labels).
  const [activeTab, setActiveTab] = useState<TabKey>('basic');
  const [errorTabs, setErrorTabs] = useState<Set<TabKey>>(new Set());

  // URL validation (create mode)
  const [urlStatus, setUrlStatus] = useState<UrlStatus>('idle');
  const [urlMessage, setUrlMessage] = useState('');
  const [downloadableCount, setDownloadableCount] = useState(0);
  const [loading, setLoading] = useState(mode === 'edit');

  // Metadata source catalog (external data sources selectable per channel)
  const [metadataSources, setMetadataSources] = useState<MetadataSourceOption[]>([]);
  // Saved required-fields snapshot (edit mode): drives the add-only picker
  // policy — previously-saved keys can never be unchecked.
  const [savedRequiredFields, setSavedRequiredFields] = useState<string[] | null>(null);

  // Field mapping (stored as JSON string for edit/view; generated by AI for create)
  const [fieldMapping, setFieldMapping] = useState<FieldMapping | null>(null);
  const [fieldMappingText, setFieldMappingText] = useState<string>(
    mode === 'create' ? DEFAULT_FIELD_MAPPING_TEXT : '',
  );
  const [analyzing, setAnalyzing] = useState(false);

  // Sidebar streaming
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [streamText, setStreamText] = useState('');
  const [sidebarStatus, setSidebarStatus] = useState<SidebarStatus>('idle');
  const [sidebarError, setSidebarError] = useState('');
  const streamBodyRef = useRef<HTMLDivElement>(null);

  // Feed preview
  const [previewEntries, setPreviewEntries] = useState<PreviewEntry[]>([]);
  const [previewParsed, setPreviewParsed] = useState<Record<string, unknown>[]>([]);
  const [previewLoading, setPreviewLoading] = useState(false);

  const fetchPreview = useCallback(
    async (url: string, fm: FieldMapping | null) => {
      if (!url) return;
      setPreviewLoading(true);
      try {
        const res = await channelsApi.previewFeed(url, fm);
        if (res.success && res.data) {
          setPreviewEntries(res.data.entries || []);
          setPreviewParsed(res.data.parsed || []);
        }
      } finally {
        setPreviewLoading(false);
      }
    },
    [],
  );

  // Auto-scroll stream
  useEffect(() => {
    if (streamBodyRef.current) {
      streamBodyRef.current.scrollTop = streamBodyRef.current.scrollHeight;
    }
  }, [streamText]);

  useEffect(() => {
    channelsApi.getFormToken().then((r) => {
      if (r.success) formTokenRef.current = r.data.token;
    });
  }, []);

  // Load the external metadata source catalog. In create mode, preselect the
  // default source (or the first available one) so the channel has a usable
  // source without requiring the user to pick explicitly.
  useEffect(() => {
    let alive = true;
    channelsApi.metadataSources().then((r) => {
      if (!alive || !r.success || !r.data) return;
      setMetadataSources(r.data.sources || []);
      if (mode === 'create') {
        const available = (r.data.sources || []).filter((s) => s.available);
        const defaultSrc = available.find((s) => s.value === r.data.default);
        const pick = defaultSrc ?? available[0];
        if (pick) {
          // Only set if the user hasn't already got a value (edit loads later).
          if (!form.getFieldValue('metadata_source')) {
            form.setFieldValue('metadata_source', pick.value);
          }
        }
      }
    });
    return () => {
      alive = false;
    };
  }, [mode, form]);

  // Load for edit
  useEffect(() => {
    if (mode === 'edit' && id) {
      channelsApi.get(id).then((r) => {
        if (r.success) {
          const ch = r.data;
          // Saved required-fields snapshot drives the add-only picker policy:
          // previously-saved keys can never be unchecked.
          setSavedRequiredFields(ch.required_metadata_fields ?? null);
          form.setFieldsValue({
            name: ch.name,
            url: ch.url,
            fetch_interval: ch.fetch_interval,
            metadata_agent_enabled: ch.metadata_agent_enabled ?? true,
            metadata_source: ch.metadata_source ?? null,
            metadata_fallback_sources: ch.metadata_fallback_sources ?? DEFAULT_FALLBACK_SOURCES,
            required_metadata_fields: ch.required_metadata_fields ?? null,
            auto_cleanup_unresolved_enabled: ch.auto_cleanup_unresolved_enabled ?? false,
            auto_cleanup_unresolved_days: ch.auto_cleanup_unresolved_days ?? 21,
            metadata_refresh_enabled: ch.metadata_refresh_enabled ?? false,
            metadata_refresh_interval_minutes: ch.metadata_refresh_interval_minutes ?? 1440,
            metadata_refresh_full_scope: ch.metadata_refresh_full_scope ?? false,
            default_is_anime: ch.default_is_anime ?? false,
          });
          if (ch.field_mapping) {
            setFieldMapping(ch.field_mapping as FieldMapping);
            setFieldMappingText(JSON.stringify(ch.field_mapping, null, 2));
            fetchPreview(ch.url, ch.field_mapping as FieldMapping);
          } else {
            fetchPreview(ch.url, null);
          }
        } else {
          message.error(t('channels.loadFailed'));
          navigate('/channels');
        }
        setLoading(false);
      });
    }
  }, [mode, id, form, fetchPreview, message, navigate, t]);

  /** Parse SSE stream */
  const consumeStream = useCallback(
    async (response: Response, onDone: (fm: FieldMapping) => void) => {
      if (!response.body) throw new Error('No response body');
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';
        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));
              if (data.type === 'delta') {
                setStreamText((p) => p + (data.content || ''));
              } else if (data.type === 'done') {
                const mapping = data.field_mapping as FieldMapping | undefined;
                if (mapping) {
                  setFieldMapping(mapping);
                  setFieldMappingText(JSON.stringify(mapping, null, 2));
                  setSidebarStatus('done');
                  onDone(mapping);
                } else {
                  setSidebarStatus('error');
                  setSidebarError(t('channels.noMapping'));
                }
              } else if (data.type === 'reset') {
                // A retry attempt started — clear the previous partial text.
                setStreamText('');
              } else if (data.type === 'error') {
                setSidebarStatus('error');
                setSidebarError(data.message || t('channels.analysisFailed'));
              }
            } catch {
              /* ignore */
            }
          }
        }
      }
    },
    [t],
  );

  const handleAnalyze = useCallback(async () => {
    const url = form.getFieldValue('url');
    if (!url) {
      message.warning(t('channels.enterUrlFirst'));
      return;
    }
    setAnalyzing(true);
    setStreamText('');
    setSidebarError('');
    setSidebarStatus('streaming');
    setSidebarOpen(true);
    // The analysis UI lives in Tab 1's right column.
    setActiveTab('basic');

    try {
      const res =
        mode === 'edit' && id
          ? await channelsApi.analyzeStream(id)
          : await channelsApi.analyzeUrlStream(url);
      if (!res.ok) {
        let err = t('channels.requestFailed');
        try {
          const body = await res.json();
          err = body?.error?.message || err;
        } catch {
          /* ignore */
        }
        setSidebarStatus('error');
        setSidebarError(err);
        setAnalyzing(false);
        return;
      }
      await consumeStream(res, (mapping) => {
        message.success(t('channels.mappingGenerated'));
        fetchPreview(url, mapping);
      });
    } catch {
      setSidebarStatus('error');
      setSidebarError(t('channels.analysisFailed'));
    }
    setAnalyzing(false);
  }, [mode, id, form, message, t, consumeStream, fetchPreview]);

  // Auto-trigger field mapping analysis after URL validation succeeds (create mode only)
  const autoAnalyzeTriggered = useRef(false);
  useEffect(() => {
    if (
      mode === 'create' &&
      urlStatus === 'valid' &&
      !fieldMappingText.trim() &&
      !autoAnalyzeTriggered.current &&
      !analyzing
    ) {
      autoAnalyzeTriggered.current = true;
      handleAnalyze();
    }
  }, [mode, urlStatus, analyzing, fieldMappingText, handleAnalyze]);
  useEffect(() => {
    if (urlStatus === 'idle' || urlStatus === 'checking') {
      autoAnalyzeTriggered.current = false;
    }
  }, [urlStatus]);

  const validateUrl = async () => {
    const url = form.getFieldValue('url');
    if (!url) return;
    setUrlStatus('checking');
    const res = await channelsApi.validateUrl(url);
    if (res.success && res.data.valid) {
      setUrlStatus('valid');
      setDownloadableCount(res.data.downloadable_count);
      setUrlMessage(
        t('channels.validFeed', { count: res.data.item_count, torrent: res.data.downloadable_count }),
      );
      fetchPreview(url, null);
    } else {
      setUrlStatus('invalid');
      setUrlMessage(res.data?.message || res.error?.message || t('channels.invalidUrl'));
    }
  };

  const closeSidebar = useCallback(() => {
    setSidebarOpen(false);
  }, []);

  const handlePreviewRefresh = useCallback(() => {
    if (!fieldMappingText.trim()) {
      if (fieldMapping) fetchPreview(form.getFieldValue('url'), fieldMapping);
      return;
    }
    try {
      const fm = JSON.parse(fieldMappingText) as FieldMapping;
      setFieldMapping(fm);
      const url = form.getFieldValue('url');
      if (url) fetchPreview(url, fm);
    } catch {
      message.error(t('channels.mappingJsonError'));
    }
  }, [fieldMapping, fieldMappingText, fetchPreview, form, message, t]);

  const handleSubmit = async (values: {
    name: string;
    url: string;
    fetch_interval: number;
    metadata_agent_enabled?: boolean;
    metadata_source?: MetadataSource | null;
    metadata_fallback_sources?: string[];
    required_metadata_fields?: string[] | null;
    auto_cleanup_unresolved_enabled?: boolean;
    auto_cleanup_unresolved_days?: number;
    metadata_refresh_enabled?: boolean;
    metadata_refresh_interval_minutes?: number | null;
    metadata_refresh_full_scope?: boolean;
    default_is_anime?: boolean;
  }) => {
    setErrorTabs(new Set());

    // Parse field mapping text if edit mode
    let fm: FieldMapping | null = fieldMapping;
    if (fieldMappingText) {
      try {
        fm = JSON.parse(fieldMappingText);
      } catch {
        message.error(t('channels.mappingJsonError'));
        setActiveTab('basic');
        return;
      }
    }

    if (!fm || !fm.field_mappings || Object.keys(fm.field_mappings).length === 0) {
      message.error(t('channels.mappingRequired'));
      setActiveTab('basic');
      return;
    }

    if (savingRef.current) return;
    savingRef.current = true;
    setSaving(true);

    const token = formTokenRef.current;
    formTokenRef.current = null;

    try {
      if (mode === 'create') {
        if (urlStatus === 'invalid') {
          message.error(t('channels.rssValidationFailed'));
          savingRef.current = false;
          setSaving(false);
          return;
        }
        const res = await channelsApi.create(
          {
            name: values.name,
            url: values.url,
            fetch_interval: values.fetch_interval,
            type: 'rss_feed',
            field_mapping: fm,
            metadata_agent_enabled: values.metadata_agent_enabled ?? true,
            metadata_source: values.metadata_agent_enabled ? (values.metadata_source ?? null) : null,
            metadata_fallback_sources: values.metadata_fallback_sources ?? [],
            // Omitted when never configured → backend applies the locked
            // baseline default.
            required_metadata_fields: values.required_metadata_fields ?? undefined,
            auto_cleanup_unresolved_enabled: values.auto_cleanup_unresolved_enabled ?? false,
            auto_cleanup_unresolved_days: values.auto_cleanup_unresolved_days ?? 21,
            metadata_refresh_enabled: values.metadata_refresh_enabled ?? false,
            metadata_refresh_interval_minutes: values.metadata_refresh_interval_minutes ?? null,
            metadata_refresh_full_scope: values.metadata_refresh_full_scope ?? false,
            default_is_anime: values.default_is_anime ?? false,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success(t('channels.created'));
          navigate('/channels');
        } else {
          message.error(res.error?.message || t('channels.createFailed'));
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      } else if (id) {
        const res = await channelsApi.update(
          id,
          {
            name: values.name,
            url: values.url,
            fetch_interval: values.fetch_interval,
            field_mapping: fm,
            metadata_agent_enabled: values.metadata_agent_enabled ?? true,
            metadata_source: values.metadata_agent_enabled ? (values.metadata_source ?? null) : null,
            metadata_fallback_sources: values.metadata_fallback_sources ?? [],
            // Add-only policy: the form value always starts from the saved
            // selection, so this can only add keys (or be omitted untouched).
            required_metadata_fields: values.required_metadata_fields ?? undefined,
            auto_cleanup_unresolved_enabled: values.auto_cleanup_unresolved_enabled ?? false,
            auto_cleanup_unresolved_days: values.auto_cleanup_unresolved_days ?? 21,
            metadata_refresh_enabled: values.metadata_refresh_enabled ?? false,
            metadata_refresh_interval_minutes: values.metadata_refresh_interval_minutes ?? null,
            metadata_refresh_full_scope: values.metadata_refresh_full_scope ?? false,
          },
          token ?? undefined,
        );
        if (res.success) {
          message.success(t('channels.updated'));
          navigate(`/channels/${id}`);
        } else {
          message.error(res.error?.message || t('channels.updateFailed'));
          channelsApi.getFormToken().then((r) => {
            if (r.success) formTokenRef.current = r.data.token;
          });
        }
      }
    } finally {
      savingRef.current = false;
      setSaving(false);
    }
  };

  /** Cross-tab validation: mark failing tabs and jump to the first one. */
  const handleFinishFailed = useCallback(({ errorFields }: { errorFields?: { name?: unknown }[] }) => {
    const fields = errorFields || [];
    const tabs = new Set<TabKey>();
    for (const ef of fields) {
      const k = tabKeyForField(ef.name);
      if (k) tabs.add(k);
    }
    setErrorTabs(tabs);
    const first = fields.length ? tabKeyForField(fields[0].name) : null;
    if (first && first !== activeTab) {
      setActiveTab(first);
    }
  }, [activeTab]);

  if (loading) {
    return <Spin style={{ display: 'flex', justifyContent: 'center', padding: 48 }} />;
  }

  const tabLabel = (key: TabKey, label: string) => (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
      {label}
      {errorTabs.has(key) && <span className="tab-error-dot" />}
    </span>
  );

  return (
    <div className="channel-form-layout">
      <div className={`channel-form-main ${activeTab !== 'basic' ? 'full' : ''}`}>
        <Title level={3} style={{ marginBottom: 24 }}>
          {mode === 'create' ? t('channels.newChannel') : t('channels.editChannel')}
        </Title>

        <Card>
          <Form
            form={form}
            layout="vertical"
            onFinish={handleSubmit}
            onFinishFailed={handleFinishFailed}
            initialValues={
              mode === 'create'
                ? {
                    name: '',
                    url: '',
                    fetch_interval: 1800,
                    metadata_agent_enabled: true,
                    metadata_source: null,
                    metadata_fallback_sources: DEFAULT_FALLBACK_SOURCES,
                    auto_cleanup_unresolved_enabled: false,
                    auto_cleanup_unresolved_days: 21,
                    metadata_refresh_enabled: false,
                    metadata_refresh_interval_minutes: 1440,
                    metadata_refresh_full_scope: false,
                    default_is_anime: false,
                  }
                : undefined
            }
          >
            <Tabs
              activeKey={activeTab}
              onChange={(k) => setActiveTab(k as TabKey)}
              items={[
                {
                  key: 'basic',
                  label: tabLabel('basic', t('channels.tabBasic')),
                  forceRender: true,
                  children: (
                    <BasicInfoTab
                      mode={mode}
                      urlStatus={urlStatus}
                      urlMessage={urlMessage}
                      downloadableCount={downloadableCount}
                      fieldMapping={fieldMapping}
                      fieldMappingText={fieldMappingText}
                      setFieldMappingText={setFieldMappingText}
                      analyzing={analyzing}
                      onValidateUrl={validateUrl}
                      onUrlChange={() => setUrlStatus('idle')}
                      onAnalyze={handleAnalyze}
                      onPreviewRefresh={handlePreviewRefresh}
                    />
                  ),
                },
                {
                  key: 'metadata',
                  label: tabLabel('metadata', t('channels.tabMetadata')),
                  forceRender: true,
                  children: (
                    <MetadataSearchTab
                      mode={mode}
                      form={form}
                      metadataSources={metadataSources}
                      savedRequiredFields={savedRequiredFields}
                    />
                  ),
                },
                {
                  key: 'schedule',
                  label: tabLabel('schedule', t('channels.tabSchedule')),
                  forceRender: true,
                  children: <ScheduleTab form={form} />,
                },
              ]}
            />

            {/* Global save bar: visible from every tab. */}
            <Form.Item style={{ marginTop: 24, marginBottom: 0 }}>
              <Space>
                <Button type="primary" htmlType="submit" loading={saving}>
                  {mode === 'create' ? t('channels.createChannel') : t('common.saveChanges')}
                </Button>
                <Button onClick={() => navigate(mode === 'edit' ? `/channels/${id}` : '/channels')}>
                  {t('common.cancel')}
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>
      </div>

      {/* Right column — analysis stream + feed preview belong to Tab 1 only */}
      {activeTab === 'basic' && (
        <div className="channel-form-right">
          {/* Stream sidebar */}
          <div className={`channel-form-stream ${sidebarOpen ? 'open' : ''}`}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '10px 16px',
                borderBottom: '1px solid var(--rr-surface-card)',
              }}
            >
              <Space>
                <Wand2 size={14} style={{ color: 'var(--rr-text-muted)' }} />
                <Text strong style={{ fontSize: 13 }}>
                  {t('channels.analyze')}
                </Text>
              </Space>
              <Button
                type="text"
                size="small"
                icon={<X size={14} />}
                onClick={closeSidebar}
                style={{ color: 'var(--rr-text-muted)' }}
              />
            </div>
            <div
              ref={streamBodyRef}
              style={{
                flex: 1,
                overflow: 'auto',
                padding: '12px 16px',
                fontFamily: 'monospace',
                fontSize: 12,
                lineHeight: 1.65,
                color: 'var(--rr-text-muted)',
                whiteSpace: 'pre-wrap',
              }}
            >
              {streamText}
              {sidebarStatus === 'streaming' && <span className="stream-cursor" />}
              {sidebarStatus === 'error' && (
                <div style={{ color: 'var(--rr-error)' }}>{sidebarError}</div>
              )}
            </div>
            <div
              style={{
                padding: '8px 16px',
                borderTop: '1px solid var(--rr-surface-card)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              {sidebarStatus === 'streaming' && (
                <Space>
                  <Loader2 size={13} style={{ color: 'var(--rr-primary)', animation: 'spin 1s linear infinite' }} />
                  <Text style={{ fontSize: 12, color: 'var(--rr-primary)' }}>{t('channels.analyzing')}</Text>
                </Space>
              )}
              {sidebarStatus === 'done' && (
                <Space>
                  <CheckCircle size={13} color="var(--rr-success)" />
                  <Text style={{ fontSize: 12, color: 'var(--rr-success)' }}>{t('channels.analysisDone')}</Text>
                </Space>
              )}
              {sidebarStatus === 'error' && (
                <Space>
                  <XCircle size={13} color="var(--rr-error)" />
                  <Text style={{ fontSize: 12, color: 'var(--rr-error)' }}>{sidebarError}</Text>
                </Space>
              )}
            </div>
          </div>

          {/* Feed Preview */}
          <div className="channel-form-preview">
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '14px 16px',
                borderBottom: '1px solid var(--rr-surface-card)',
              }}
            >
              <Space>
                <Rss size={14} style={{ color: 'var(--rr-text-muted)' }} />
                <Text strong style={{ fontSize: 13 }}>
                  {t('channels.preview')}
                </Text>
                {previewEntries.length > 0 && (
                  <Text style={{ fontSize: 12, color: 'var(--rr-text-muted)' }}>
                    {previewEntries.length} {t('channels.entries')}
                  </Text>
                )}
              </Space>
              {previewEntries.length > 0 && !previewLoading && (
                <Button
                  type="text"
                  size="small"
                  icon={<RefreshCw size={13} />}
                  onClick={() => {
                    const url = form.getFieldValue('url');
                    if (url) fetchPreview(url, fieldMapping);
                  }}
                  style={{ color: 'var(--rr-text-muted)' }}
                />
              )}
            </div>
            <div style={{ flex: 1, overflow: 'auto', padding: 0 }}>
              {previewLoading ? (
                <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
                  <Spin />
                </div>
              ) : previewEntries.length === 0 ? (
                <div style={{ padding: 48, textAlign: 'center', color: 'var(--rr-text-muted)', fontSize: 13 }}>
                  {mode === 'edit' ? t('common.loading') : t('channels.enterUrlFirst')}
                </div>
              ) : (
                previewEntries.slice(0, 30).map((entry, i) => {
                  const parsed = previewParsed[i] || {};
                  const hasParsed = Object.keys(parsed).length > 0;
                  return (
                    <div
                      key={i}
                      style={{
                        padding: '12px 16px',
                        borderBottom: '1px solid var(--rr-surface-card)',
                      }}
                    >
                      <Text
                        style={{ fontSize: 13, display: 'block', marginBottom: 4, wordBreak: 'break-word' }}
                      >
                        {entry.title || 'Untitled'}
                      </Text>
                      {entry.published && (
                        <Text style={{ fontSize: 11, color: 'var(--rr-text-muted)', display: 'block', marginBottom: hasParsed ? 6 : 0 }}>
                          {new Date(entry.published).toLocaleDateString()}
                        </Text>
                      )}
                      {hasParsed && (
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                          {Object.entries(parsed)
                            .filter(([, v]) => v != null && v !== '')
                            .map(([k, v]) => (
                              <Tag
                                key={k}
                                style={{
                                  fontSize: 11,
                                  background: 'var(--rr-surface-elevated)',
                                  border: '1px solid var(--rr-border)',
                                  color: 'var(--rr-text-muted)',
                                  marginInlineEnd: 0,
                                }}
                              >
                                <span style={{ color: 'var(--rr-text-muted)' }}>{k}:</span> {String(v)}
                              </Tag>
                            ))}
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
